trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    mvn clean package
  displayName: 'Build Spring Boot Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/demo.jar'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your-Free-Azure-Subscription-Name'
    appName: 'your-web-app-name'
    package: '$(System.DefaultWorkingDirectory)/drop/demo.jar'